### ISSUE TITLE
"Attribute error" due to r.text.decode

### ISSUE THREAD

**Issue by MaleNurse** [pepe386/netdata-monerod#1]
First, thanks for making this! Couldn't get this is function out of the box, though, on my box running Ubuntu 20.10 and Python3. When examining the logs, noticed:

 "2021-01-08 19:10:14: python.d WARNING: plugin[main] : monerod[monerod] : unhandled exception on check : AttributeError("'str' object has no attribute 'decode'"), skipping the job"

Prof. Google said it was due to it trying to decode something already decoded, so I dropped the ".decode('utf-8')" in line 97 and now it's working great. I'll throw a PR over in a second.

**Comment by pepe386** [comment]
Thanks for your pull request. It works fine on my system as well. I'm glad that you find this plugin useful!
